apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: userservice
  labels:
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: userservice
  endpoints:
  - port: metrics
