apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eserver
  labels:
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: eserver
  endpoints:
  - port: metrics
