apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: contactservice
  labels:
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: contactservice
  endpoints:
  - port: metrics
