apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apiservice
  template:
    metadata:
      labels:
        app: apiservice
    spec:
      containers:
      - name: apiservice
        image: 863099/springboot-image:latest
        ports:
        - containerPort: 3000
