apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: apiservice
  labels:
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: apiservice
  endpoints:
  - port: metrics
